<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20641" started-at="2021-04-28T11:34:18Z" finished-at="2021-04-28T11:34:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20641" started-at="2021-04-28T11:34:18Z" finished-at="2021-04-28T11:34:39Z">
      <class name="testcases.UITestCase">
        <test-method status="PASS" signature="before()[pri:0, instance:testcases.UITestCase@13805618]" name="before" is-config="true" duration-ms="15732" started-at="2021-04-28T11:34:18Z" finished-at="2021-04-28T11:34:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="TC001(java.lang.String)[pri:0, instance:testcases.UITestCase@13805618]" name="TC001" duration-ms="4870" started-at="2021-04-28T11:34:34Z" data-provider="data" finished-at="2021-04-28T11:34:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Kanpur]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at pages.WeatherPage.getTemp(WeatherPage.java:36)
at testcases.UITestCase.TC001(UITestCase.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001 -->
        <test-method status="PASS" signature="after()[pri:0, instance:testcases.UITestCase@13805618]" name="after" is-config="true" duration-ms="0" started-at="2021-04-28T11:34:39Z" finished-at="2021-04-28T11:34:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- testcases.UITestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
